book_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('', include("tracker.urls")),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from tracker import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('current_books/', views.CurrentBooks.as_view(), name="current_books"),
    path('completed_books', views.CompletedBooks.as_view(), name="completed_books"),
    path('book_add/', views.BookAdd.as_view(), name="book_add")
]

htmx_views = [
    path('check_username/', views.check_username, name="check-username"),
    path('book_detail/<int:book_pk>/<str:book_type>/', views.book_detail, name="book_detail"),
    path('remove_book/<int:book_pk>/<str:book_type>/', views.remove_book, name="remove_book")
    # path('add_book/', views.add_book, name="add-book"),
    # path('delete_book/<int:pk>/', views.delete_book, name="delete-book"),
    # path('search-book/', views.search_book, name="search-book"),
    # path('clear/', views.clear, name="clear"),
    # path('sort/', views.sort, name="sort"),
    # path('book_list_partial', views.books_partial, name="book-list-partial"),
    # path('upload_cover/<int:pk>/', views.upload_cover, name="upload-cover")
]

urlpatterns += htmx_views

tracker/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.functions import Lower


class User(AbstractUser):
    pass


class Series(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=30)

    class Meta:
        verbose_name = "Series"
        verbose_name_plural = "Series"

    @property
    def total_pages(self):
        total_pages = 0
        books = SeriesBook.objects.filter(full_series_id=self.id)
        for book in books:
            obj = Book.objects.filter(series=book)
            total_pages += obj.get('page_count')

        return total_pages

    def __str__(self):
        return f"{self.title}"


class SeriesBook(models.Model):
    full_series = models.OneToOneField(Series, on_delete=models.CASCADE)
    num_in_series = models.PositiveIntegerField()

    def __str__(self):
        return f"#{self.num_in_series} in {self.full_series.title}"


class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=30)
    cover = models.ImageField(upload_to='book_covers/', null=True, blank=True)
    page_count = models.PositiveIntegerField()
    series = models.OneToOneField(SeriesBook, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = [Lower('title')]

    def __str__(self):
        return f"{self.title}"


class UserBook(models.Model):
    read_count = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        abstract = True
        unique_together = ('user', 'book')


class ToReadBook(UserBook):
    order = models.PositiveIntegerField(unique=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"{self.book.title} at #{self.order} for {self.user}"


class Read(UserBook):
    read_number = models.PositiveIntegerField()
    start_date = models.DateField()

    class Meta(UserBook.Meta):
        abstract = True


class InProgressRead(Read):
    current_page = models.PositiveIntegerField()

    @property
    def current_percent(self):
        return self.current_page / self.book.page_count * 100

    def __str__(self):
        return f"{self.user} at page {self.current_page} in {self.book.title}"


class FinishedRead(Read):
    end_date = models.DateField()

    @property
    def days_to_read(self):
        return (self.end_date - self.start_date).days

    @property
    def pages_per_day(self):
        return round(self.book.page_count / self.days_to_read, 2)

    def __str__(self):
        return f"{self.user} finished {self.book.title} at {self.end_date}"

tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from tracker.models import User, Book


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class NewBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "cover", "page_count", "series"]

tracker/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import FormView, TemplateView, ListView
from django.contrib import messages

from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods

from book_tracker import settings
from tracker.forms import RegisterForm, NewBookForm
from tracker.models import ToReadBook, InProgressRead, Series, UserBook, FinishedRead
from tracker.utils import get_max_order, reorder


class IndexView(TemplateView):
    template_name = 'index.html'


class Login(LoginView):
    template_name = 'registration/login.html'


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.save()
        return super.form_valid(form)


class CurrentBooks(LoginRequiredMixin, TemplateView):
    template_name = 'current-books.html'
    context_object_name = 'current_books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["to_read"] = ToReadBook.objects.filter(user=self.request.user)
        context["in_progress"] = InProgressRead.objects.filter(user=self.request.user)
        return context


class CompletedBooks(LoginRequiredMixin, TemplateView):
    template_name = 'completed-books.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["finished_books"] = FinishedRead.objects.filter(user=self.request.user)
        return context


class BookAdd(LoginRequiredMixin, FormView):
    form_class = NewBookForm
    template_name = 'book-add.html'
    success_url = reverse_lazy('book_add')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# HTMX
def check_username(request):
    username = request.POST.get('username')
    if get_user_model().objects.filter(username=username).exists():
        return HttpResponse("<div id='username-error' class='error'>This username already exists</div>")
    else:
        return HttpResponse("<div id='username-error' class='success'>This username is available</div>")


@login_required
def book_detail(request, book_pk, book_type):
    if book_type == 'to-read':
        user_book = get_object_or_404(ToReadBook, book_id=book_pk)
    elif book_type == 'in-progress':
        user_book = get_object_or_404(InProgressRead, book_id=book_pk)
    else:
        return

    finished_reads = FinishedRead.objects.filter(book_id=book_pk).filter(user=request.user)

    return render(request, 'partials/book-detail.html', {'user_book': user_book, 'finished_reads': finished_reads})


@login_required
@require_http_methods(['DELETE'])
def remove_book(request, book_pk, book_type):
    if book_type == 'to-read':
        ToReadBook.objects.get(book_id=book_pk, user=request.user).delete()
        reorder(request.user)
        books = ToReadBook.objects.filter(user=request.user)
        return render(request, 'partials/to-read-list.html', {'to-read': books})
    elif book_type == 'in-progress':
        InProgressRead.objects.get(book_id=book_pk, user=request.user).delete()
        books = InProgressRead.objects.filter(user=request.user)
        return render(request, 'partials/in-progress-list.html', {'in-progress': books})
    else:
        return


# @login_required
# def add_book(request):
#     title = request.POST.get('booktitle')
#
#     book = Book.objects.get_or_create(title=title)[0]
#
#     if not UserBook.objects.filter(book=book, user=request.user).exists():
#         UserBook.objects.create(
#             book=book,
#             user=request.user,
#             order=get_max_order(request.user)
#         )
#
#     books = UserBook.objects.filter(user=request.user)
#     messages.success(request, f"Added {title} to book list")
#     return render(request, 'partials/book-list.html', {'books': books})
#
#
# @login_required
# def search_book(request):
#     search_text = request.POST.get('search')
#
#     userbooks = UserBook.objects.filter(user=request.user)
#     results = Book.objects.filter(name__icontains=search_text).exclude(
#         name__in=(userbooks.values_list('book__title', flat=True))
#     )
#     context = {"results": results}
#     return render(request, 'partials/search-results.html', context)
#
#
# def clear(request):
#     return HttpResponse("")
#
#
# def sort(request):
#     book_pks_order = request.POST.getlist('book_order')
#     books = []
#     updated_books = []
#
#     userbooks = UserBook.objects.prefetch_related('book').filter(user=request.user)
#     for idx, book_pk in enumerate(book_pks_order, start=1):
#         userbook = next(u for u in userbooks if u.pk == int(book_pk))
#
#         if userbook.order != idx:
#             userbook.order = idx
#             updated_books.append(userbook)
#
#         books.append(userbook)
#
#     UserBook.objects.bulk_update(updated_books, ['order'])
#     context = {'books': books}
#
#     return render(request, 'partials/book-list.html', context)
#
#
# @login_required
# def books_partial(request):
#     books = UserBook.objects.filter(user=request.user)
#     return render(request, 'partials/book-list.html', {'books': books})
#
#
# @login_required
# def upload_cover(request, pk):
#     userbook = get_object_or_404(UserBook, pk=pk)
#     cover = request.FILES.get('cover')
#     userbook.book.cover.save(cover.name, cover)
#     context = {'userbook': userbook}
#     return render(request, 'partials/book-detail.html', context)

tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Book Tracker App</title>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <!-- Bootstrap CSS -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.9.9"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

    <!-- Quicksand Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    {% include 'partials/navbar.html' %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Modal Placeholder -->
    <div id="modal" class="modal fade" tabindex="-1">
        <div id="dialog" class="modal-dialog modal-xl"></div>
    </div>
    <!-- Modal Trigger -->
    <script src="{% static 'dialog.js' %}"></script>

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })

        htmx.onLoad(function(content) {
            let sortables = content.querySelectorAll(".sortable");
            for (let i = 0; i < sortables.length; i++) {
                let sortable = sortables[i];
                new Sortable(sortable, {
                    animation: 150,
                    ghostClass: 'blue-background-class'
                });
            }
        })
    </script>
</body>
</html>

tracker/templates/book-add.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="page-header text-center col-8 offset-2 mb-4">
        Enter New Book Information
    </div>

    <div class="col-6 offset-3 pt-4">
        <form method="POST" action="{% url 'book_add' %}" autocomplete="off">
            {% csrf_token %}

            <div class="form-floating mb-3">
                {{ form.title.errors }}
                {% render_field form.title class="form-control" id="floatingInput" placeholder="Enter Book Title" %}
                <label for="floatingInput">Title</label>
            </div>
            <div class="form-floating mb-3">
                {{ form.author.errors }}
                {% render_field form.author class="form-control" id="floatingInput" placeholder="Enter Book Author" %}
                <label for="floatingInput">Author</label>
            </div>
            <label class="form-label" for="id_cover">Cover</label>
            <div class="input-group mb-3">
                {{ form.cover.errors }}
                {% render_field form.cover class="form-control" placeholder="Enter Book Author" %}
            </div>
            <div class="form-floating mb-3">
                {{ form.page_count.errors }}
                {% render_field form.page_count class="form-control" id="floatingInput" placeholder="Enter Page Count" %}
                <label for="floatingInput">Page Count</label>
            </div>

            <button class="btn-success btn-enter px-2 my-4" type="submit">Enter Book</button>
        </form>
    </div>

{% endblock content %}

tracker/templates/books.html
{% extends 'base.html' %}

{% block content %}

    {% include 'partials/logged-in-header.html' %}

    <div class="row justify-content-between text-center">
        <div id="to-read-list" class="col-6">
            {% include 'partials/to-read-list.html' %}
        </div>

        <div id="in-progress-list" class="col-6">
            {% include 'partials/in-progress-list.html' %}
        </div>
    </div>

{% endblock content %}

tracker/templates/completed-books.html
{% extends 'base.html' %}
{% load possessive %}

{% block content %}
    <div class="page-header text-center col-8 offset-2 mb-5">
        {{ request.user.username|possessive|title }} Completed Books
    </div>

    <div class="row justify-content-between gap-1">
        <div id="completed-books" class="d-flex col-8 flex-column">
            {% include 'partials/finished-books.html' %}
        </div>
        <div id="book-filters" class="d-flex col-3 flex-column">
            {% include 'partials/book-filters.html' %}
        </div>
    </div>

{% endblock content %}

tracker/templates/current-books.html
{% extends 'base.html' %}
{% load possessive %}

{% block content %}

    <div class="page-header text-center col-8 offset-2 mb-4">
        {{ request.user.username|possessive|title }} Books
    </div>

    <div class="row justify-content-between">
        <div id="to-read-list" class="d-flex col-6 flex-column">
            {% include 'partials/to-read-list.html' %}
        </div>

        <div id="in-progress-list" class="d-flex col-6 flex-column">
            {% include 'partials/in-progress-list.html' %}
        </div>
    </div>

{% endblock content %}

tracker/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/welcome-header.html' %}

{% endblock content %}